apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - sonarr-deploy.yml
  - sonarr-svc.yml
  - sonarr-ing.yml
  - sonarr-infisical-sync.yml
  - sealedsecret.yaml
