apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - readarr-deploy.yml
  - readarr-svc.yml
  - readarr-ing.yml
  - readarr-infisical-sync.yml
  - sealedsecret.yaml