apiVersion: v2
appVersion: 9.1.11
description: A Helm chart to deploy Reflector
home: https://github.com/emberstack/kubernetes-reflector
icon: https://raw.githubusercontent.com/emberstack/kubernetes-reflector/main/assets/helm_icon.png
keywords:
- reflector
- controller
- copy
- secrets
- configmaps
- cert-manager
- certificates
maintainers:
- email: helm-charts@emberstack.com
  name: winromulus
name: reflector
sources:
- https://github.com/emberstack/kubernetes-reflector
type: application
version: 9.1.11
