apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jelly
resources:
  - jellystat-deploy.yml
  - jellystat-svc.yml
  - jellystat-pvc.yml
  - jellystat-infisical-sync.yml
  - sealedsecret.yaml
