apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jelly
resources:
  - overseerr-deploy.yml
  - overseerr-svc.yml
  - overseerr-pvc.yml
  - overseerr-ing.yml
  - overseerr-infisical-sync.yml
  - sealedsecret.yaml