apiVersion: v1
kind: Service
metadata:
  name: prowrr-exporter
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.253.45
  selector:
    app: prowrr-exporter
  type: LoadBalancer
  ports:
    - port: 9707
      targetPort: prowrr-monit