apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - libretranslate-deploy.yaml
  - libretranslate-svc.yaml
  - libretranslate-ing.yaml
  - libretranslate-configmap.yaml
  - libretranslate-pvc.yml