apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - unpackerr-trt-deploy.yml
  - unpackerr-trt-svc.yml
  - unpackerr-trt-infisical-sync.yml
  - sealedsecret.yaml