apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - linkwarden-deploy.yml
  - linkwarden-svc.yml
  - linkwarden-pvc.yml
  - linkwarden-ing.yml
  - linkwarden-infisical-sync.yml
  - sealedsecret.yaml
