apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jelly
resources:
  - jellyfin/jellyfin-deploy.yml
  - jellyfin/jellyfin-svc.yml
  - jellyfin/jellyfin-pvc.yml
  - jellystat/jellystat-deploy.yml
  - jellystat/jellystat-svc.yml
  - jellystat/jellystat-pvc.yml
  - overseerr/overseerr-deploy.yml
  - overseerr/overseerr-svc.yml
  - overseerr/overseerr-pvc.yml