apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: keel
    app.kubernetes.io/name: keel
  name: keel
spec:
  ingressClassName: nginx
  rules:
  - host: keel.vinicima.com
    http:
      paths:
      - backend:
          service:
            name: keel
            port:
              name: keel
        path: /
        pathType: Prefix
  - host: keel-k8s.vinicima.com
    http:
      paths:
      - backend:
          service:
            name: keel
            port:
              name: keel
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - keel.vinicima.com
    - keel-k8s.vinicima.com
    secretName: vinicima-com-tls
