apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - bazarr-deploy.yml
  - bazarr-svc.yml
  - bazarr-ing.yml
  - sealedsecret.yaml
  - bazarr-infisical-sync.yml