apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - vault-deploy.yml
  - vault-svc.yml
  - vault-pvc.yml
  - vault-ing.yml
  - vault-infisical-sync.yml
  - sealedsecret.yaml
