apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - qrcode-deploy.yml
  - qrcode-svc.yml
  - qrcode-configmap.yml
  - qrcode-pvc.yml
  - qrcode-ing.yml
  - qrcode-infisical-sync.yml
  - sealedsecret.yaml
