apiVersion: v1
kind: Service
metadata:
  name: sonarr-exporter
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.253.49
  selector:
    app: sonarr-exporter
  type: LoadBalancer
  ports:
    - port: 9707
      targetPort: sonarr-monit