apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - uptime-kuma-deployment.yaml
  - uptime-kuma-ingress.yaml
  - uptime-kuma-service.yaml
  - uptime-kuma-test-connection.yaml
