apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - lingarr-deploy.yml
  - lingarr-svc.yml
  - lingarr-ing.yml
  - sealedsecret.yaml
  - lingarr-pvc.yml
  - lingarr-infisical-sync.yml