apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - radarr-deploy.yml
  - radarr-svc.yml
  - radarr-ing.yml
  - sealedsecret.yaml
  - radarr-infisical-sync.yml