apiVersion: v1
kind: Service
metadata:
  name: radarraexporter
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.253.46
  selector:
    app: radarraexporter
  type: LoadBalancer
  ports:
    - port: 9707
      targetPort: radarramonit