apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - lingarr-animes-deploy.yml
  - lingarr-animes-svc.yml
  - lingarr-animes-ing.yml
  - sealedsecret.yaml
  - lingarr-animes-pvc.yml
  - lingarr-animes-infisical-sync.yml