apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - github.com/metallb/metallb/config/frr?ref=v0.15.2
  - ipaddresspoll.yaml
  - advertisement.yaml