apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - lidarr-deploy.yml
  - lidarr-svc.yml
  - lidarr-ing.yml
  - lidarr-infisical-sync.yml
  - sealedsecret.yaml
