apiVersion: v1
kind: Service
metadata:
  name: radarr-exporter
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.253.47
  selector:
    app: radarr-exporter
  type: LoadBalancer
  ports:
    - port: 9707
      targetPort: radarr-monit