apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - whisparr-deploy.yml
  - whisparr-svc.yml
  - whisparr-ing.yml
  - whisparr-infisical-sync.yml
  - sealedsecret.yaml