apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - prowlarr-deploy.yml
  - prowlarr-svc.yml
  - prowlarr-ing.yml
  - prowlarr-infisical-sync.yml
  - sealedsecret.yaml
