apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: igpu
resources:
  - photoprism-mgabriel-deploy.yml
  - photoprism-mgabriel-svc.yml
  - sealedsecret.yaml
  - photoprism-mgabriel-ing.yml
  - photoprism-mgabriel-infisical-sync.yml
