apiVersion: v1
kind: Service
metadata:
  name: sonarraexporter
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.253.48
  selector:
    app: sonarraexporter
  type: LoadBalancer
  ports:
    - port: 9707
      targetPort: sonarramonit