apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: igpu
resources:
  - photoprism-ksoares-deploy.yml
  - photoprism-ksoares-svc.yml
  - sealedsecret.yaml
  - photoprism-ksoares-ing.yml
  - photoprism-ksoares-infisical-sync.yml
